version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: product_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: product_cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
