version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: product_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: product_cache
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    command: server --console-address :9001 /data

  app:
    build: .
    container_name: product_service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - minio
    environment:
      PORT: 8080
      API_VERSION: ${API_VERSION}

      JWT_SECRET: ${JWT_SECRET}

      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      MINIO_ENDPOINT: minio:9000
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      PRODUCT_CACHE_TTL: ${PRODUCT_CACHE_TTL}

volumes:
  db_data:
  minio_data:
