version: '3.8'

services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      JWT_SECRET: JWT_SECRET_CKXEDQBVK
      JWT_REFRESH_SECRET: JWT_REFRESH_SECRET_CKXEDQBVK
      PORT: 8081
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: postgres
      DB_PORT: 5433
      API_VERSION: v1
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: auth_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
